<a href="https://colab.research.google.com/github/Adamphoenix003/ML_Learning_curve/blob/main/00startingwithPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()


7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
matrix = torch.tensor([[7, 8],
                        [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.size()

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
TENSOR[0][0]

tensor([1, 2, 3])

In [16]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4597, 0.4050, 0.0880, 0.2882],
        [0.1877, 0.7392, 0.9998, 0.6361],
        [0.6844, 0.6847, 0.2878, 0.4277]])

In [17]:
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width and 3 color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [18]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
ten_zeroes = torch.zeros_like(input =one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor.dtype

torch.float32

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [22]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what data type is the tensor
                               device=None,#what device is your tensor on
                               requires_grad=False #whether or not to track gradients with this tensors operations
                               )
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [24]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [25]:
some_tensor = torch.rand([3, 4])

some_tensor

tensor([[0.9276, 0.3254, 0.5463, 0.1078],
        [0.3538, 0.0053, 0.1406, 0.0582],
        [0.9401, 0.6752, 0.1136, 0.6372]])

In [26]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9276, 0.3254, 0.5463, 0.1078],
        [0.3538, 0.0053, 0.1406, 0.0582],
        [0.9401, 0.6752, 0.1136, 0.6372]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
