<a href="https://colab.research.google.com/github/Adamphoenix003/ML_Learning_curve/blob/main/00startingwithPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()


7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim


1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
matrix = torch.tensor([[7, 8],
                        [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [15]:
TENSOR.size()

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
TENSOR[0][0]

tensor([1, 2, 3])

In [19]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5406, 0.2560, 0.2381, 0.0859],
        [0.6257, 0.4943, 0.2103, 0.8506],
        [0.5105, 0.4020, 0.6847, 0.4730]])

In [20]:
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width and 3 color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)